timezone: Australia/Brisbane

sources:
  - name: Australian Border Force
    feed: "https://www.abf.gov.au/_layouts/15/AppPages/Rss.aspx?site=newsroom"   # ABF newsroom RSS
  - name: Department of Social Services
    feed: "https://www.dss.gov.au/rss/updates.xml"                               # DSS site updates RSS
  - name: Department of Employment and Workplace Relations (DEWR)
    homepage: "https://www.dewr.gov.au/newsroom"
    selector: "a[href^='/newsroom/'], a[href*='/newsroom/']"
    timeout: 45                                                                   # give this one longer
  - name: Australian Taxation Office (ATO)
    feed: "https://www.ato.gov.au/rss/media-centre.xml"                           # official media centre RSS
  - name: Australian Competition & Consumer Commission (ACCC)
    homepage: "https://www.accc.gov.au/about-us/news"                             # new news hub
    selector: "a[href*='/media-release/'], a[href*='/speech/']"
