timezone: Australia/Brisbane

# Tip: start with a handful, then expand.
# The fetcher will try to autodetect RSS/Atom from each page.
# If it can't, it will fall back to scraping with the provided CSS selector (if any).

sources:
  - name: Digital Transformation Agency
    feed: https://www.dta.gov.au/news-and-blogs/latest/feed/all
    selector: article a

  - name: Department of Finance
    homepage: https://www.finance.gov.au/news
    selector: article a

  - name: Department of Health and Aged Care
    homepage: https://www.health.gov.au/news
    selector: article a

  - name: Department of Home Affairs
    homepage: https://www.homeaffairs.gov.au/news-media
    selector: a

  - name: Department of Climate Change, Energy, the Environment and Water
    homepage: https://www.dcceew.gov.au/news
    selector: article a

  - name: Department of Infrastructure, Transport, Regional Development, Communications and the Arts
    homepage: https://www.infrastructure.gov.au/media
    selector: article a

  - name: Department of Education
    homepage: https://www.education.gov.au/news
    selector: article a

  - name: Department of Employment and Workplace Relations
    homepage: https://www.dewr.gov.au/newsroom
    selector: article a

  - name: Department of Social Services
    homepage: https://www.dss.gov.au/about-the-department/news
    selector: article a

  - name: Australian Taxation Office
    homepage: https://www.ato.gov.au/Media-centre/
    selector: a

  - name: Australian Securities & Investments Commission (ASIC)
    homepage: https://www.asic.gov.au/newsroom/media-releases/
    selector: a

  - name: Australian Competition & Consumer Commission (ACCC)
    homepage: https://www.accc.gov.au/media/media-releases
    selector: a
