name: Fetch & Deploy

on:
  schedule:
    - cron: "10 14 * * *"     # daily ~00:10 Brisbane
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.commit.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run fetcher
        run: python scripts/fetch.py

      - name: Commit data (if changed)
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- web/data/ ; then
            git add web/data/
            git commit -m "chore: update daily data ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
            git push
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: fetch
    if: needs.fetch.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
